/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sketcher (https://sketchfab.com/jnanbr07)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/samsung-s24-ultra-b05e35cc5fa540cba52e055b378c28bd
Title: Samsung s24 ultra
*/
'use client'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function PhoneModel(props) {
  const { nodes, materials } = useGLTF('models/samsung_s24_ultra/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[1.126, 2.455, 0]} scale={1.856}>
        <group position={[-0.012, -0.134, 0]} scale={[0.539, 0.539, 0.061]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_9.geometry}
            material={materials['Material.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_11.geometry}
            material={materials.Silver}
          />
        </group>
        <group position={[-0.032, -0.081, 0]} scale={[0.539, 0.539, 0.07]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_14.geometry}
            material={materials['Material.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_16.geometry}
            material={materials.Screen}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_19.geometry}
          material={materials.Silver}
          position={[-0.371, 0.821, 0.05]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.113, 0.051, 0.113]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_22.geometry}
          material={materials.Silver}
          position={[-0.371, 0.554, 0.05]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.113, 0.051, 0.113]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_25.geometry}
          material={materials.Silver}
          position={[-0.371, 0.292, 0.05]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.113, 0.051, 0.113]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_28.geometry}
          material={materials.Silver}
          position={[-0.131, 0.56, 0.055]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.072, 0.032, 0.072]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_31.geometry}
          material={materials.Silver}
          position={[-0.131, 0.817, 0.055]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.072, 0.032, 0.072]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_34.geometry}
          material={materials['Material.001']}
          position={[-0.373, 0.822, 0.069]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.094, 0.004, 0.094]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_37.geometry}
          material={materials['Material.001']}
          position={[-0.373, 0.558, 0.069]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.094, 0.004, 0.094]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_40.geometry}
          material={materials['Material.001']}
          position={[-0.373, 0.296, 0.069]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.094, 0.004, 0.094]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_43.geometry}
          material={materials['Material.001']}
          position={[-0.13, 0.818, 0.07]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.061, 0.003, 0.061]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_46.geometry}
          material={materials['Material.001']}
          position={[-0.133, 0.56, 0.07]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.061, 0.003, 0.061]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_49.geometry}
          material={materials['Material.004']}
          position={[-0.373, 0.821, 0.103]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.096, 0.004, 0.096]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_52.geometry}
          material={materials['Material.004']}
          position={[-0.371, 0.556, 0.103]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.098, 0.004, 0.098]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_55.geometry}
          material={materials['Material.004']}
          position={[-0.373, 0.291, 0.103]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.096, 0.004, 0.096]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_58.geometry}
          material={materials['Material.004']}
          position={[-0.131, 0.818, 0.085]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.064, 0.003, 0.064]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_61.geometry}
          material={materials['Material.004']}
          position={[-0.131, 0.56, 0.085]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.064, 0.003, 0.064]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_64.geometry}
          material={materials.Silver}
          position={[0, -1.274, 0.003]}
          scale={[0.074, 0.032, 0.003]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_67.geometry}
          material={materials.Flash}
          position={[-0.131, 0.688, 0.082]}
          scale={[0.028, 0.028, 0.007]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_70.geometry}
          material={materials.Lens}
          position={[-0.375, 0.823, 0.082]}
          scale={[0.032, 0.032, 0.019]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_73.geometry}
          material={materials.Lens}
          position={[-0.375, 0.556, 0.082]}
          scale={[0.032, 0.032, 0.019]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_76.geometry}
          material={materials.Lens}
          position={[-0.375, 0.295, 0.082]}
          scale={[0.039, 0.039, 0.023]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_79.geometry}
          material={materials.Lens}
          position={[-0.133, 0.556, 0.082]}
          scale={[0.022, 0.022, 0.013]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_82.geometry}
          material={materials.Screen}
          position={[-0.375, 0.825, 0.067]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.049, 0.028, 0.049]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_85.geometry}
          material={materials.Screen}
          position={[-0.375, 0.555, 0.067]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.049, 0.028, 0.049]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_88.geometry}
          material={materials.Screen}
          position={[-0.375, 0.295, 0.067]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.055, 0.031, 0.055]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_91.geometry}
          material={materials.Screen}
          position={[-0.133, 0.558, 0.067]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.033, 0.019, 0.033]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_94.geometry}
          material={materials['Material.001']}
          position={[-0.507, 0.057, 0]}
          scale={[0.105, 0.084, 0.019]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_97.geometry}
          material={materials['Material.001']}
          position={[0.469, -1.213, -0.001]}
          scale={[0.035, 0.102, 0.026]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_100.geometry}
          material={materials['Material.001']}
          position={[-0.507, 0.427, 0]}
          scale={[0.105, 0.152, 0.019]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('models/samsung_s24_ultra/scene.gltf')
